### ISSUE TITLE
CARMA_fixed_sigma: incorrect description of the parameters

### ISSUE THREAD

**Issue by Sodbo** [ZikunY/CARMA#13]
Dear CARMA team,

I am using the CARMA package for fine mapping (BTW - thanks for your work!). 

I have faced a few problems with the description of [CARMA_fixed_sigma_normal](https://github.com/ZikunY/CARMA/blob/master/R/CARMA_fixed_sigma_normal.R) function, which prevents fine-tuning of the function for the purposes of large-scale analysis. I would appreciate if you would have a look at the comments below.

Many thanks!

Sodbo Sharapov

1. Line 16 : **BF.index: A number smaller than 1 to specifying the threshold of the Bayes factor of the estimated credible models. The default setting is 3.2.**
1.a: I assume it is not 3.2, but 1 / 3.2
1.b: Line 54 : In the function's code, the default value is: **BF.index = 10**. This is a contradiction. Can you please clarify and fix it, if needed?
2. Line 56 : The function's parameter **outlier.BF.index = 1 / 3.2** (Line 56) lacks description, while parameter **outlier.threshold** (Line 18) does not exist in the code but is described in the description section.
2a. One may guess that** outlier.BF.index and** outlier.threshold** are the same instances. Nevertheless, it could be clearer.
2b. Line 18 **outlier.threshold | The Bayes threshold of the hypothesis testing of determining outliers, which is 10 by default.**. But the default value is not concordant with the description and is **outlier.BF.index = 1/3.2**.
4. Line 56 : The function's parameter **tau = 0.04** lacks of description
5. Line 56: The function's parameter **prior.prob.computation = "Logistic"** lacks description.

**Comment by ZikunY** [comment]
Hi Sodbo, 

 Thank you for reaching out and pointing out the incorrect description. We will update the manual and description as soon as possible. Thanks again. 

Best,
Zikun
