### ISSUE TITLE
Installation issue : undefined symbol: dpocon_

### ISSUE THREAD

**Issue by Mickokoch** [ZikunY/CARMA#2]
Hi, I would like to use this R package but unfortunately I get this issue while installing CARMA with devtools:

```
Error: package or namespace load failed for ‘CARMA’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/mfisun/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-CARMA/00new/CARMA/libs/CARMA.so':
  /mfisun/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-CARMA/00new/CARMA/libs/CARMA.so: undefined symbol: dpocon_
Error: loading failed
```

I can't find this error anywhere on the internet, checked all the dependencies, tried different R versions but the problem still remains.
Have you ever encountered this error and do you have any idea how I could fix it ?

**Comment by PaulTimmers** [comment]
I encountered the same error and managed to fix it by switching to a different BLAS/LAPACK library. Specifically, I installed the Intel MLK version using the tutorial from https://csantill.github.io/RPerformanceWBLAS/.

**Comment by Mickokoch** [comment]
It worked !
Thank you for your help
