### ISSUE TITLE
Saving Outlier RDS File as RData File

### ISSUE THREAD

**Issue by mconery** [ZikunY/CARMA#23]
Hi Zikun,

I noticed that the code that saves the outlier checking results has a slight error in it. Specifically, the following line is saving an RDS file, but the file extension is for an RData file:

saveRDS(conditional.S.list,file=paste0(output.labels,'/post_', label,'_','outliers.RData')) 

If you try to open the RData objects, they throw an error unless you manually change the extension back to ".rds". This is obviously a minor issue, but it should also be really easy to fix.

Best,
Mitch

**Comment by ZikunY** [comment]
Hi Mitch, 

 Thank you so much for pointing out the bug here. For unknown reasons, I had been saving ".rds" file with ".RData" extension for so long...... Glad you picked it up here, appreciate for the help. 

Best,
Zikun
