### ISSUE TITLE
Error at loading the package

### ISSUE THREAD

**Issue by stepanv1** [ZikunY/CARMA#6]
Hello!
Istallation goes successfully.
Attempting loading the library I get this:
library("CARMA")
Error: package or namespace load failed for ‘CARMA’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/stepangrinek/R/x86_64-pc-linux-gnu-library/4.1/CARMA/libs/CARMA.so':
  /home/stepangrinek/R/x86_64-pc-linux-gnu-library/4.1/CARMA/libs/CARMA.so: undefined symbol: dsyevd_

Can you help?

**Comment by hlnicholls** [comment]
I ran into this error and following some of the steps that resolved a [another issue](https://github.com/ZikunY/CARMA/issues/2) worked for me. Not sure why though. At any rate, if it's helpful, I resolved my ```CARMA.so: undefined symbol: dsyevd_``` error by checking the Intel MLK installation instructions (in https://csantill.github.io/RPerformanceWBLAS/) and in particular this line, followed by re-running installation, solved it:

```
sudo apt-get install libopenblas-base libatlas3-base
```

**Comment by ZikunY** [comment]
@hbliu Hi Hongbo,

Thank you so much for this help! I will add these solutions to the vignette accordingly. Really appreciate it.

Best,
Zikun
