### ISSUE TITLE
no method or default for coercing “matrix” to “dMatrix”

### ISSUE THREAD

**Issue by Hiuyu** [ZikunY/CARMA#7]
Hi Zikun,
I met an error when following CARMA_dome.pdf as follows.
```R
> CARMA.results<-CARMA_fixed_sigma(z.list,ld.list,lambda.list=lambda.list, outlier.switch=F)`
Error in as(matrix(0, nrow = nrow(x), ncol = p), "dMatrix") : 
  no method or default for coercing “matrix” to “dMatrix”
```

After traceback to the "CARMA.R" file, I supposed the error arise from the lack of a method to convert 'matrix' to 'dMatrix'.  
```R
index.fun.inner<-function(x){
      m<-as(as(as(matrix(0,nrow=nrow(x),ncol=p), "dMatrix"), "generalMatrix"), "TsparseMatrix")
      m@i<-as.integer(rep(1:nrow(x)-1,each=ncol(x)))
      m@j<-as.integer(c(t(x))-1)
      m@x=rep(1,nrow(x)*ncol(x))
      m<-as(m,"CsparseMatrix")
      return(m)
    }
```

Could you please provide some suggestions?

**Comment by ZikunY** [comment]
@Hiuyu This is due to the update of Matrix package, where the expression of as(,"dgTMatrix") has been deprecated. Please try R/4.2.2, it should fix the problem. But please do let me know if the error remains. Thank you!

**Comment by oma219** [comment]
@ZikunY @Hiuyu   Hello, are there any updates on this? I ran into a similar error. I was using R v4.2.3 and tried R v4.2.2 but that didn't work. I tried downgrading my Matrix version from 1.4.1 to 1.3.0 but that didn't work. Let me know if there is any consensus for what version is problematic. Thank you!

**Comment by ZikunY** [comment]
Hi, 

That is strange, it should work fine now. Did you try using R 4.2.3 coupled with Matrix 1.4.1? Maybe that would work. Please let me know if there is still errors. 

Best,
Zikun

**Comment by oma219** [comment]
Hi Zikun, 
Thanks for the response. Yes I tried that but it was not working. I recently did upgrade the R version to 4.3.1 and that upgraded by Matrix version to 1.6.1 and it seemed to work better. I am still combing through the log files, but if I find any other issues I'll let you know. But right now, I think it is working now for me.
